version: 2

sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         loaded_at_field: "CAST(date_date AS TIMESTAMP)"
         freshness:
          warn_after: {count: 90, period: day}
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: foreign key to ship
           - name: products_id
             description: foreign key to product
           - name: revenue
             description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
           - name: quantity
             description: the quantity of products purchased for a given order
         tests:
           - unique:
              column_name: "(orders_id || '-' || pdt_id)"
       - name: product
         identifier: raw_gz_product
         description: product of Greenweez
         columns:
           - name: products_id
             description: Primary key
             tests:
               - unique
               - not_null
           - name: purchase_price
             description: the purchase price of the product
       - name: ship
         identifier: raw_gz_ship
         description: shipping data for Greenweez orders
         columns:
           - name: orders_id
             description: Primary key
           - name: shipping_fee
             description: the price the customer pays for shipping
           - name: log_cost
             description: the cost of preparing the parcel in the distribution centre/warehouse
           - name: ship_cost
             description: shipping cost paid by Greenweez to the carrier/logistics provider

       - name: adwords
         identifier: raw_gz_adwords
       - name: bing
         identifier: raw_gz_bing
       - name: criteo
         identifier: raw_gz_criteo
       - name: facebook
         identifier: raw_gz_facebook

models:
   - name: int_sales_margin
     description: margin calcultation per order
     columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: products_id
         description: products key
         tests:
           - not_null
       - name: margin
         description: Margin = Revenue - Purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: Purchase_cost = Quantity * Purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
     tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"


   - name: int_campaigns
     description: "Data from all campaigns across multiple sources."
     columns:
      - name: date_date
        description: "Date of the campaign record."
        tests:
          - not_null

      - name: paid_source
        description: "Source from which the campaign originates (AdWords, Bing, Criteo, Facebook)."
        tests:
          - not_null

      - name: campaign_key
        description: "Unique identifier for each campaign."
        tests:
          - not_null

      - name: campaign_name
        description: "Name of the campaign."
        tests:
          - not_null

      - name: ads_cost
        description: "Cost of ads for each campaign."
        tests:
          - not_null

      - name: impression
        description: "Number of impressions for the campaign."
        tests:
          - not_null

      - name: click
        description: "Number of clicks for the campaign."
        tests:
          - not_null

     tests:
      - unique:
          column_name: "(campaign_key || '-' || date_date)"


   - name: int_campaigns_day
     description: "Daily aggregated data from all campaigns, with totals for ads cost, impressions, and clicks."
     columns:
      - name: date_date
        description: "Date of the campaign data, aggregated on a daily basis."
        tests:
          - not_null 
          - unique  

      - name: ads_cost
        description: "Total cost of ads for all campaigns on a given day."
        tests:
          - not_null 

      - name: ads_impressions
        description: "Total number of impressions for all campaigns on a given day."
        tests:
          - not_null 


      - name: ads_clicks
        description: "Total number of clicks for all campaigns on a given day."
        tests:
          - not_null 


   - name: finance_campaigns_day
     description: "Aggregated financial and campaign data on a daily basis, including ad costs, revenue, margin, and logistics costs."
     columns:
      - name: date_date
        description: "Date of the aggregated data for both campaigns and finance."
        tests:
          - not_null 
          - unique 

      - name: ads_margin
        description: "Operational margin minus ad costs, rounded to two decimal places."

      - name: average_basket
        description: "Average basket value for the day, rounded to two decimal places."
        tests:
          - not_null

      - name: operational_margin
        description: "Operational margin for all activities on a given day."

      - name: ads_cost
        description: "Total ad cost for the day from all campaigns."

      - name: ads_impressions
        description: "Total number of ad impressions for the day from all campaigns."

      - name: ads_clicks
        description: "Total number of ad clicks for the day from all campaigns."

      - name: total_quantity
        description: "Total quantity of items sold on the given day."

      - name: revenue
        description: "Total revenue generated on the given day."

      - name: total_purchase_cost
        description: "Total purchase cost of items sold on the given day."

      - name: margin
        description: "Margin calculated as revenue minus total purchase cost."

      - name: total_shipping_fee
        description: "Total shipping fees for the day."

      - name: total_log_cost
        description: "Total logistics cost for the day."




